import { chromium } from 'playwright';
const SP=process.env.SP;
const errs=[];
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--use-gl=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage({viewport:{width:1440,height:900}});
p.on('pageerror',e=>errs.push(e.message));
p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
await p.goto('http://localhost:4174/es/contacto',{waitUntil:'networkidle'});
await p.getByRole('button',{name:/Empezar la conversación/i}).scrollIntoViewIfNeeded();
await p.waitForTimeout(400);
await p.screenshot({path:SP+'/launcher.png'});
await p.getByRole('button',{name:/Empezar la conversación/i}).click();
await p.waitForTimeout(1200);
await p.screenshot({path:SP+'/stage-1.png'});
await p.keyboard.type('Carlos Ramírez'); await p.keyboard.press('Enter'); await p.waitForTimeout(700);
await p.keyboard.type('carlos@meetbecome.com'); await p.keyboard.press('Enter'); await p.waitForTimeout(700);
await p.keyboard.type('Flum'); await p.keyboard.press('Enter'); await p.waitForTimeout(900);
await p.screenshot({path:SP+'/stage-2.png'});
const m=await b.newPage({viewport:{width:390,height:780}});
await m.goto('http://localhost:4174/es/contacto',{waitUntil:'networkidle'});
await m.getByRole('button',{name:/Empezar la conversación/i}).click();
await m.waitForTimeout(1200);
await m.screenshot({path:SP+'/stage-m.png'});
console.log(errs.length?errs.join('\n'):'sin errores');
await b.close();
